version: '2'
services: 
  api:
    build: .
    volumes:
      - .:/go/src/TaxCalc
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tax-db
    ports:
      - 5432:5432
  migrate:
    image: api:latest
    command: bee migrate -driver=postgres -conn="postgres://postgres:password@postgres/tax-db?sslmode=disable"
    depends_on:
      - api
      - postgres

networks:
  default:
    driver: bridge